/* auto-generated by zig-addon */
/* eslint-disable */
export declare function run_binding_demo(): boolean;
export declare function hilog_demo(message: string): void;
export declare function forward_stdio_to_hilog(): boolean;
export declare function configure_hilog(): void;
export declare function check_self_permission(permission: string): boolean;
